package main

import (
	"context"
	"database/sql"
	"fmt"
	"io/ioutil"
	"os"
	"path"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/ArtemGretsov/golang-server-template/config"
	"github.com/ArtemGretsov/golang-server-template/src/database"
)

const currentDir = "./src/database/migrations/"
const currentFileName = "migration.go"

func main() {
	topLevelArg := os.Args[1]

	switch topLevelArg {
	case "generate":
		GenerateMigration()
	case "up":
		Up()
	case "down":
		Down()
	}
}

/* Generate migration */

func GenerateMigration() {
	client := database.DB()
	defer client.Close()

	timestamp := time.Now().UnixNano()
	migrationName := os.Args[2]
	upMigrationName := fmt.Sprintf("%d_%s.up.sql", timestamp, migrationName)
	upMigrationPath := path.Join(currentDir, upMigrationName)
	downMigrationName := fmt.Sprintf("%d_%s.down.sql", timestamp, migrationName)
	downMigrationPath := path.Join(currentDir, downMigrationName)

	creatingFile, err := os.Create(upMigrationPath)
	checkPanic(err)

	err = client.Schema.WriteTo(context.Background(), creatingFile)
	checkPanic(err)
	creatingFile.Close()

	openingFile, err := os.Open(upMigrationPath)
	checkPanic(err)

	defer openingFile.Close()

	migrationContent, err := ioutil.ReadAll(openingFile)
	checkPanic(err)

	rawMigrationContent := regexp.
		MustCompile(`BEGIN;\n(.+)\nCOMMIT;\n`).
		ReplaceAll(migrationContent, []byte("$1"))

	err = os.WriteFile(upMigrationPath, rawMigrationContent, 0644)
	checkPanic(err)

	err = os.WriteFile(downMigrationPath, []byte(""), 0644)
	checkPanic(err)

	fmt.Println("Migration have been successfully generated.")
	fmt.Println("Please write migration * .down.sql manually!")
	fmt.Println()
}
/* ------------------ */


/* Migration Up */

func Up() {
	serverConfig := config.Get()
	db, err := sql.Open("postgres", serverConfig["POSTGRES_CONNECT_STRING"])
	checkPanic(err)
	defer db.Close()

	_, err = db.Query(`create table if not exists migrations(
    id  bigint generated by default as identity constraint migrations_pkey primary key,
    date_create timestamp default NOW(),
    name    varchar not null
	)`)
	checkPanic(err)

	ctx := context.Background()
	tx, err := db.BeginTx(ctx, nil)
	checkPanic(err)

	_, err = tx.ExecContext(ctx, "lock table migrations in exclusive mode")
	checkPanic(err)

	files := getMigrationFileNames()
	transactionNameHashTable := map[string]bool{}
	rows, err := tx.QueryContext(ctx, "select name from migrations")
	defer rows.Close()

	for rows.Next() {
		var name string
		err = rows.Scan(&name)
		checkPanic(err)
		transactionNameHashTable[name] = true
	}

	var filesForExec []string

	for _, fileName := range files {
		isUp := strings.Contains(fileName, "up.sql")

		if !isUp {
			continue
		}

		migrationName := getMigrationName(fileName)

		if !transactionNameHashTable[migrationName] {
			filesForExec = append(filesForExec, fileName)
		}
	}

	if len(filesForExec) == 0 {
		fmt.Println("No migrations found to update.")
	}

	for _, migrationName := range filesForExec {
		migrationPath := path.Join(currentDir, migrationName)
		migrationFile, err := os.Open(migrationPath)
		checkPanic(err)

		migrationContent, err := ioutil.ReadAll(migrationFile)
		checkPanic(err)

		_, err = tx.ExecContext(ctx, string(migrationContent))
		checkPanic(err)

		_, err = tx.Exec("insert into migrations(name) values($1)", getMigrationName(migrationName))
		fmt.Println(migrationName + " - successful!")
	}

	err = tx.Commit()
	checkPanic(err)
}

func getMigrationName(name string) string {
	return regexp.
		MustCompile(`(.+)\.up\.sql`).
		ReplaceAllString(name, "$1")
}

func getMigrationFileNames() []string {
	var files []string
	allFiles, err := ioutil.ReadDir(currentDir)
	checkPanic(err)

	for _, f := range allFiles {
		if currentFileName != f.Name() {
			files = append(files, f.Name())
		}
	}

	sort.Strings(files)
	return files
}
/* ------------------ */


/* Down migration */

func Down()  {
	serverConfig := config.Get()
	db, err := sql.Open("postgres", serverConfig["POSTGRES_CONNECT_STRING"])
	checkPanic(err)
	defer db.Close()

	ctx := context.Background()
	tx, err := db.BeginTx(ctx, nil)
	checkPanic(err)

	_, err = tx.ExecContext(ctx, "lock table migrations in exclusive mode")
	checkPanic(err)

	rows, err := tx.QueryContext(ctx, "select name from migrations order by date_create limit 1")
	defer rows.Close()

	var migrationName string

	for rows.Next() {
		err = rows.Scan(&migrationName)
		checkPanic(err)
	}

	if migrationName == "" {
		fmt.Println("No migrations found to down.")

		err = tx.Commit()
		checkPanic(err)
		return
	}

	downMigrationName := migrationName + ".down.sql"
	downMigrationPath := path.Join(currentDir, downMigrationName)

	downMigrationFile, err := os.Open(downMigrationPath)
	checkPanic(err)

	downMigrationContent, err := ioutil.ReadAll(downMigrationFile)
	checkPanic(err)

	_, err = tx.ExecContext(ctx, string(downMigrationContent))
	checkPanic(err)

	_, err = tx.ExecContext(ctx, "delete from migrations where name=$1", migrationName)

	err = tx.Commit()
	checkPanic(err)

	fmt.Println(downMigrationName + " - successful!")
}
/* ------------------ */


func checkPanic(err error) {
	if err != nil {
		panic(err)
	}
}
