version: "3"
services:
  app:
    build:
      dockerfile: ./test.Dockerfile
      context: .
    depends_on:
      - postgres
    command: bash -c 'go run ./scripts/wait_for_postgres.go; make migrate-up; make test'

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=app_test
      - POSTGRES_PASSWORD=app_test
      - POSTGRES_DB=app_test
    logging:
      driver: none
